export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'About',
    headline: 'Welcome to AxieSwap! Here you will find the most wonderful collection of Axies to rent you ever did see!',
    description: 'swap axies with your friends',
    buttonLabel: 'Get Started', 
    imgStart: false,
    img: require('../../assets/images/axieOutline.png'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Connect your wallet',
    headline: 'Welcome to AxieSwap! Here you will find the most wonderful collection of Axies to rent you ever did see!',
    description: 'swap axies with your friends',
    buttonLabel: 'Learn More', 
    imgStart: true,
    img: require('../../assets/images/axieOutline.png'),
    alt: 'Car',
    dark: false,
    primary: false,
    darkText: true,
}

export const homeObjThree = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'AxieSwap',
    headline: 'Welcome to AxieSwap! Here you will find the most wonderful collection of Axies to rent you ever did see!',
    description: 'swap axies with your friends',
    buttonLabel: 'Start Now', 
    imgStart: false,
    img: require('../../assets/images/axieOutline.png'),
    alt: 'Car',
    dark: false,
    primary: false,
    darkText: false,
}